### Zellij shell session manager
[".local/bin/zellij"]
	type = "archive-file" 
{{ if eq .chezmoi.os "darwin" }} 
	url = "https://github.com/zellij-org/zellij/releases/download/{{ .zellijVersion }}/zellij-aarch64-apple-darwin.tar.gz"
{{ else }}
	url = "https://github.com/zellij-org/zellij/releases/download/{{ .zellijVersion }}/zellij-x86_64-unknown-linux-musl.tar.gz"
{{ end }}
	path = "zellij"

### Starship shell
[".local/bin/starship"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }} 
	url = "https://github.com/starship/starship/releases/download/{{ .starshipVersion }}/starship-aarch64-apple-darwin.tar.gz"
{{ else }}
	url = "https://github.com/starship/starship/releases/download/{{ .starshipVersion }}/starship-x86_64-unknown-linux-musl.tar.gz"
{{ end }}
	path = "starship"


### Helix editor
[".local/bin/hx"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/helix-editor/helix/releases/download/{{ .helixVersion }}/helix-{{ .helixVersion }}-aarch64-macos.tar.xz"
{{ else }}
  url = "https://github.com/helix-editor/helix/releases/download/{{ .helixVersion }}/helix-{{ .helixVersion }}-x86_64-linux.tar.xz"
{{ end }}
  path = "hx"
	stripComponents = 1

[".config/helix"]
	type = "archive"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/helix-editor/helix/releases/download/{{ .helixVersion }}/helix-{{ .helixVersion }}-aarch64-macos.tar.xz"
{{ else }}
  url = "https://github.com/helix-editor/helix/releases/download/{{ .helixVersion }}/helix-{{ .helixVersion }}-x86_64-linux.tar.xz"
{{ end }}
	stripComponents = 1
  include = ["*/runtime/**"]

[".config/fish/completions/hx.fish"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/helix-editor/helix/releases/download/{{ .helixVersion }}/helix-{{ .helixVersion }}-aarch64-macos.tar.xz"
{{ else }}
  url = "https://github.com/helix-editor/helix/releases/download/{{ .helixVersion }}/helix-{{ .helixVersion }}-x86_64-linux.tar.xz"
{{ end }}
	stripComponents = 3
  path = "hx.fish"

### ASDF version manager
[".asdf"]
	type = "git-repo"
	url = "https://github.com/asdf-vm/asdf.git"
	clone.args = ["--branch={{ .asdfVersion }}"]


### Delta diff renderer
[".local/bin/delta"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/dandavison/delta/releases/download/{{ .deltaVersion }}/delta-{{ .deltaVersion }}-aarch64-apple-darwin.tar.gz"
{{ else }}
  url = "https://github.com/dandavison/delta/releases/download/{{ .deltaVersion }}/delta-{{ .deltaVersion }}-x86_64-unknown-linux-musl.tar.gz"
{{ end }}
  path = "delta"
	stripComponents = 1

### Lazygit
[".local/bin/lazygit"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/jesseduffield/lazygit/releases/download/v{{ .lazygitVersion }}/lazygit_{{ .lazygitVersion }}_Darwin_arm64.tar.gz"
{{ else }}
  url = "https://github.com/jesseduffield/lazygit/releases/download/v{{ .lazygitVersion }}/lazygit_{{ .lazygitVersion }}_Linux_x86_64.tar.gz"
{{ end }}
  path = "lazygit"

### Lazydocker
[".local/bin/lazydocker"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/jesseduffield/lazydocker/releases/download/v{{ .lazydockerVersion }}/lazydocker_{{ .lazydockerVersion }}_Darwin_arm64.tar.gz"
{{ else }}
  url = "https://github.com/jesseduffield/lazydocker/releases/download/v{{ .lazydockerVersion }}/lazydocker_{{ .lazydockerVersion }}_Linux_x86_64.tar.gz"
{{ end }}
  path = "lazydocker"

### Ripgrep
[".local/bin/rg"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ .ripgrepVersion }}/ripgrep-{{ .ripgrepVersion }}-aarch64-apple-darwin.tar.gz"
{{ else }}
  url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ .ripgrepVersion }}/ripgrep-{{ .ripgrepVersion }}-x86_64-unknown-linux-musl.tar.gz"
{{ end }}
  path = "rg"
  stripComponents = 1

[".config/fish/completions/rg.fish"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ .ripgrepVersion }}/ripgrep-{{ .ripgrepVersion }}-aarch64-apple-darwin.tar.gz"
{{ else }}
  url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ .ripgrepVersion }}/ripgrep-{{ .ripgrepVersion }}-x86_64-unknown-linux-musl.tar.gz"
{{ end }}
  path = "rg.fish"
  stripComponents = 2

### Ripgrep
[".local/bin/fd"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/sharkdp/fd/releases/download/{{ .fdVersion }}/fd-{{ .fdVersion }}-aarch64-apple-darwin.tar.gz"
{{ else }}
  url = "https://github.com/sharkdp/fd/releases/download/{{ .fdVersion }}/fd-{{ .fdVersion }}-x86_64-unknown-linux-musl.tar.gz"
{{ end }}
  path = "fd"
  stripComponents = 1

[".config/fish/completions/fd.fish"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/sharkdp/fd/releases/download/{{ .fdVersion }}/fd-{{ .fdVersion }}-aarch64-apple-darwin.tar.gz"
{{ else }}
  url = "https://github.com/sharkdp/fd/releases/download/{{ .fdVersion }}/fd-{{ .fdVersion }}-x86_64-unknown-linux-musl.tar.gz"
{{ end }}
  path = "fd.fish"
  stripComponents = 2

### Fonts
{{ $fontDir := "" }}
{{ if eq .chezmoi.os "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{ else }}
{{-     $fontDir = ".local/share/fonts" }}
{{ end }}
# FiraCode NF
["{{ $fontDir }}/JetBrainsMonoNF"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ .nerdFontVersion }}/JetBrainsMono.tar.xz"
    exclude = ["*.md"]

["{{ $fontDir }}/UbuntuMonoNF"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ .nerdFontVersion }}/UbuntuMono.tar.xz"
    exclude = ["*.md"]

["{{ $fontDir }}/UbuntuNF"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ .nerdFontVersion }}/Ubuntu.tar.xz"
    exclude = ["*.md"]

