zellijVersion = "v0.40.1"
starshipVersion = "v1.19.0"
helixVersion = "24.03"
asdfVersion = "v0.14.0"
nerdFontVersion = "v3.2.1"
deltaVersion = "0.17.0"
lazygitVersion = "0.42.0"
lazydockerVersion = "0.23.3"
ripgrepVersion = "14.1.0"
fdVersion = "v10.1.0"
ollamaVersion = "v0.3.11"
