{{ $zellijVersion := "0.40.1" }}
[".local/bin/zellij"]
	type = "archive-file" 
{{ if eq .chezmoi.os "darwin" }} 
	url = "https://github.com/zellij-org/zellij/releases/download/v{{ $zellijVersion }}/zellij-x86_64-unknown-linux-musl.tar.gz"
{{ else }}
	url = "https://github.com/zellij-org/zellij/releases/download/v{{ $zellijVersion }}/zellij-aarch64-apple-darwin.tar.gz"
{{ end }}
	path = "zellij"
