### Zellij shell session manager
[".local/bin/zellij"]
	type = "archive-file" 
{{ if eq .chezmoi.os "darwin" }} 
	url = "https://github.com/zellij-org/zellij/releases/download/{{ .zellijVersion }}/zellij-aarch64-apple-darwin.tar.gz"
{{ else }}
	url = "https://github.com/zellij-org/zellij/releases/download/{{ .zellijVersion }}/zellij-x86_64-unknown-linux-musl.tar.gz"
{{ end }}
	path = "zellij"

### Starship shell
[".local/bin/starship"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }} 
	url = "https://github.com/starship/starship/releases/download/{{ .starshipVersion }}/starship-aarch64-apple-darwin.tar.gz"
{{ else }}
	url = "https://github.com/starship/starship/releases/download/{{ .starshipVersion }}/starship-x86_64-unknown-linux-musl.tar.gz"
{{ end }}
	path = "starship"


### Helix editor
[".local/bin/hx"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/helix-editor/helix/releases/download/{{ .helixVersion }}/helix-{{ .helixVersion }}-aarch64-macos.tar.xz"
{{ else }}
  url = "https://github.com/helix-editor/helix/releases/download/{{ .helixVersion }}/helix-{{ .helixVersion }}-x86_64-linux.tar.xz"
{{ end }}
  path = "hx"
	stripComponents = 1

[".config/helix"]
	type = "archive"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/helix-editor/helix/releases/download/{{ .helixVersion }}/helix-{{ .helixVersion }}-aarch64-macos.tar.xz"
{{ else }}
  url = "https://github.com/helix-editor/helix/releases/download/{{ .helixVersion }}/helix-{{ .helixVersion }}-x86_64-linux.tar.xz"
{{ end }}
	stripComponents = 1
  include = ["*/runtime/**"]

[".config/fish/completions/hx.fish"]
	type = "archive-file"
{{ if eq .chezmoi.os "darwin" }}
  url = "https://github.com/helix-editor/helix/releases/download/{{ .helixVersion }}/helix-{{ .helixVersion }}-aarch64-macos.tar.xz"
{{ else }}
  url = "https://github.com/helix-editor/helix/releases/download/{{ .helixVersion }}/helix-{{ .helixVersion }}-x86_64-linux.tar.xz"
{{ end }}
	stripComponents = 3
  path = "hx.fish"

